name: Java CI

on:
    push:
      branches: 
        - main
    pull_request:
      branches:
        - main

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'
      
      - name: Build
        working-directory: ./complete
        run: ./mvnw clean compile
  
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: 
      - compile
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'
      
      - name: Testing
        working-directory: ./complete
        run: ./mvnw clean test
  
  package:
    name: Package
    runs-on: ubuntu-latest
    needs: 
      - compile
      - test
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: '17'
      
      - name: Package
        working-directory: ./complete
        run: ./mvnw clean package -DskipTests
      
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: generated_artifact
          path: complete/target/spring-boot-complete-*.jar
          if-no-files-found: error

  
    
    
        


